name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown pyyaml beautifulsoup4
    - name: Build all documentation
      run: |
        export TUNA_TEMP_DIR=$(mktemp -d)
        cat enabled.txt | xargs python global/compile.py -v --lang zh -C dom -C tuna
        git checkout transpiled
        mv $TUNA_TEMP_DIR/* .
    - name: Commit changes
      run: |
        git config --local user.name  "GitHub Actions"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add *.md
        git commit -am "build documentations" && git push || echo "No changes to commit"
